# Site settings
title: Image Batch Processor
description: A cross-platform, open source tool for batch image processing
email: adam+github@twardoch.com
author: Adam Twardoch
url: https://twardoch.github.io/ibp
baseurl: "/ibp"
logo: /assets/img/ibp-sm.png

# Social
repo: "https://github.com/twardoch/ibp"
github_user: "twardoch"
github_repo: "ibp"
twitter: adamtwar

# Theme configuration
remote_theme: vsoch/mkdocs-jekyll
color: "#8c1515"
logo_width: 34
accentColor: red
themeColor: red
fixedNav: 'true'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-assets

# Navigation
nav:
  - Home: /
  - Features: /features
  - Installation: /installation
  - Usage: /usage
  - Contributing: /contributing
  - License: /license
  - GitHub Repository: https://github.com/twardoch/ibp

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:title/
markdown_ext: md
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      author: "Adam Twardoch"

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - CHANGELOG.md
  - LICENSE
  - README.md

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# Custom variables
custom:
  feature_image: /assets/img/feature-image.png
  show_downloads: true
