# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Image Batch Processor
description: A cross-platform, open source tool for batch image processing
email: adam+github@twardoch.com
author: Adam Twardoch
url: https://twardoch.github.io/ibp # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ibp" # the subpath of your site, e.g. /blog
logo: /assets/img/ibp-sm.png

# Social
repo: "https://github.com/twardoch/ibp"
github_user: "twardoch"
github_repo: "ibp"
twitter: adamtwar

# Theme configuration
remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Search config
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # If true, the search will focus on the first search result after 250ms. This might feel too fast or too slow - if so, adjust the value in _includes/js/just-the-docs.js
  # Supports true or false (default)
  # focus_search_result: false
  # If true, the search will focus on the search input when the page is loaded, and users can start typing immediately. This is useful when you have a search-centric site (like a search engine) or when you have hidden the search bar by default.
  # Supports true or false (default)
  # auto_focus_search: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Image Batch Processor on GitHub":
    - "//github.com/twardoch/ibp"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
# nav_external_links:
#   - title:
#     url:
#   - title:
#     url:
#     hide_icon: true # optional: hide the external link icon
#     opens_in_new_tab: true # optional: open link in new tab

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
footer_content: "Copyright © 2025 Adam Twardoch. Distributed by an <a href=\"https://github.com/twardoch/ibp/tree/main/LICENSE\">MIT license</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/twardoch/ibp" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Enable or disable this site serving as a progressive web application
# pwa:
#   enabled: false

# Define the color scheme, see docs/customization.md#colors for all possible values.
color_scheme: dark

# Advanced options (rarely need to be set)
# Exclude specific pages from being searched
# search_exclude:
#   - /search.html
#   - /collection-search-results.html
# Includes an alternate footer "nav" for pages
# You can set this option to a custom liquid file at _includes/custom_nav_footer.html
# nav_footer_custom:

# Advanced customization
# The following options are advanced configurations for specific use cases.
# You should not need to set them for a regular JTD project
# For developers: changes to the following options should be backwards-compatible with older versions of the theme

# Includes a custom search header for pages. Can be overriden for individual pages by setting `search_header_custom` in the page's front matter.
# search_header_custom: _includes/search_header_custom.html

# The URL of your website (used for canonical link tag, Open Graph tags, and sitemaps). Include the protocol and hostname:
# url: "https://just-the-docs.com"

# Includes a custom navigation footer for pages. You can set this option to a custom liquid file at _includes/custom_nav_footer.html
# nav_footer_custom:

# Specifies the site title to be used in Open Graph tags. If this option is not set, site.title is used.
# og_site_title:

# Specifies the open graph type, e.g., website or article. If this option is not set, the default is website.
# og_type:

# Specifies the site name to be used in Open Graph tags. If this option is not set, the default is the repository name from github-metadata, or if that's not available, site.title
# og_site_name:

# Specifies the URL to the site's Open Graph image. This option overrides the og_image option, but is itself overridden on a page-by-page basis by og_image (see below).
# og_image_url:

# Specifies the path on the site to the site's Open Graph image. This option is overridden by og_image_url, but is itself overridden on a page-by-page basis by og_image (see below).
# og_image:

# Specifies the width of the site's Open Graph image in pixels.
# og_image_width:

# Specifies the height of the site's Open Graph image in pixels.
# og_image_height:

# Specifies the color mode of the site's Open Graph image. This can be used to automatically invert the colors of the image for dark mode in supported clients. Values can be "light", "dark", or "auto".
# og_image_color_mode:

# Set a custom copyright, defaults to site.author or site.title.
# copyright:

# Specifies the error mode for Liquid. This can be set to warn, error, or strict. See https://shopify.github.io/liquid/basics/configuration/
# liquid:
#   error_mode: "warn"

# External navigation links
# nav_external_links:
#   - title:
#     url:
#   - title:
#     url:
#     hide_icon: true # optional: hide the external link icon
#     opens_in_new_tab: true # optional: open link in new tab

# Specifies kramdown options as described at https://kramdown.gettalong.org/options.html
# kramdown:
#   parse_block_html: true

# Specifies the auto ids used for headings, to be compatible with pure kramdown
# this option is not recommended unless you are migrating from a different theme
# kramdown:
#   auto_ids: false

# Specifies the HTML to doc conversion used by kramdown. Other options are GFM and kramdown.
# this option is not recommended unless you are migrating from a different theme
# kramdown:
#   input: Kramdown

# Specifies a base path for resolving anchor links. This is useful if you are using a custom baseurl with a trailing slash, or if you are deploying to GitHub Pages on a project repository.
# Note that this option is not supported by kramdown; the helper include must be used instead.
# docs_baseurl:

# Specifies a path to a local version of the mermaid JS library, for offline use.
# mermaid:
#   path: "/assets/js/vendor/mermaid.min.js"

# Enables a callouts block quote style. See https://just-the-docs.com/docs/ui-components/callouts/ for more information.
# callouts:
#   warning:
#     title: Warning
#     color: red

# Enables a set of basic MathJax macros for defining bold, italics, etc. See https://just-the-docs.com/docs/ui-components/mathjax/ for more information.
# enable_mathjax: true

# Google Analytics: change UA-XXXX-X to be your site's ID
# ga_tracking: UA-XXXX-X
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

# Pin this version of the theme
# remote_theme: just-the-docs/just-the-docs@v0.5.4

# Disable usage of নাশদ and metadata plugins since these require a local build, and are not supported on GitHub Pages' auto builds.
# plugins:
#   - jekyll-seo-tag
#   - jekyll-github-metadata

# These collections are used by Just the Docs in the theme layout and default data structures. Users can add to them, but removing them may cause unexpected issues.
# collections:
#   docs:
#     permalink: "/:collection/:path/"
#     output: true
#   posts:
#     permalink: "/blog/:year/:month/:day/:title/"
#     output: true

# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/